apiVersion: v1
kind: Service
metadata:
  name: workflow-service
  namespace: atlas
  labels:
    app: workflow-service
    app.kubernetes.io/part-of: atlas
spec:
  selector:
    app: workflow-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
