apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: atlas
  labels:
    app: identity-service
    app.kubernetes.io/part-of: atlas
spec:
  selector:
    app: identity-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
